---

parameters:
   FunctionArn: !stack_output wise.yaml::FunctionArn
   ScheduleExpression: >-
      cron(25 15 1 * ? *)
   State: ENABLED

sceptre_user_data:
   wise:
      amount: 10
      amount_side: source
      reference: Foreign currency savings
      source_currency: EUR
      target_currency: CHF

stack_tags:
   Purpose: twecs

template_path: sceptre/schedule.py
