---

parameters:
   FunctionArn: !stack_output wise.yaml::FunctionArn
   ScheduleExpression: >-
      cron(30 9 L * ? *)
   State: ENABLED

sceptre_user_data:
   wise:
      amount: 10
      amount_side: source
      reference: Foreign currency savings
      source_currency: EUR
      target_currency: SGD

stack_tags:
   Purpose: scheduled currency exchanges
   exchange-purpose: savings

template_path: sceptre/schedule.py
