---

parameters:
   RepositoryBucket: !stack_output repository.yaml::BucketName
   GitCommitId: >-
      f47ffd53a4c6b211f20d5ded0a3b0e7066408ad2
   PythonPackageName: twecs.aws.lambda
   PythonVersions:
      - python3.8

stack_tags:
   Purpose: scheduled currency exchanges

template_path: cloudformation/layer.yaml
