---

parameters:
   RepositoryBucket: !stack_output repository.yaml::BucketName
   GitCommitId: >-
      4bd246fdcbce0bfa0ad292493b80947163b6ce66
   PythonPackageName: twecs.aws.lambda
   PythonVersions:
      - python3.8

stack_tags:
   Purpose: twecs

template_path: cloudformation/layer.yaml
