---

parameters:
   RepositoryBucket: !stack_output repository.yaml::BucketName
   GitCommitId: >-
      69aa4f3dc98cfacd6683c38b9fb0247c6bd3323d
   PythonPackageName: twecs.aws.lambda
   PythonVersions:
      - python3.8

stack_tags:
   Purpose: scheduled currency exchanges

template_path: cloudformation/layer.yaml
