---

parameters:
   RepositoryBucket: !stack_output repository.yaml::BucketName
   GitCommitId: >-
      9bda836a765587dd391f62bdc8f21114cdca2aff
   PythonPackageName: twecs.aws.lambda
   PythonVersions:
      - python3.8

stack_tags:
   Purpose: twecs

template_path: cloudformation/layer.yaml
