---

parameters:
   RepositoryBucket: !stack_output repository.yaml::BucketName
   GitCommitId: >-
      293ab9759f85386e6a48fa38d23c3023baca9f92
   PythonPackageName: twecs.wise
   PythonVersions:
      - python3.8

stack_tags:
   Purpose: scheduled currency exchanges

template_path: cloudformation/layer.yaml
