---

parameters:
   RepositoryBucket: !stack_output repository.yaml::BucketName
   GitCommitId: >-
      657a17ec76694273969836c14fde90688d873d8d
   PythonPackageName: twecs.wise
   PythonVersions:
      - python3.8

stack_tags:
   Purpose: scheduled currency exchanges

template_path: cloudformation/layer.yaml
