---

parameters:
   IamPath: /twecs/
   Layers:
      - !stack_output layers/core.yaml::LatestVersionArn
      - !stack_output layers/wise.yaml::LatestVersionArn
   Policies:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
   PythonVersion: '{{ python_version }}'
   WiseApiBaseUrl: https://api.transferwise.com
   WiseApiKey: {{ var.wise_api_key }}

stack_tags:
   Purpose: scheduled currency exchanges

template_path: cloudformation/wise.yaml
