---

name: Code linting

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize

jobs:
  Python:
    name: Lint Python code
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out pertinent branch
        uses: actions/checkout@v3
        with:
          # git history isn't necessary
          fetch-depth: 1
      -
        name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      -
        name: Install Flake8
        run: >-
          pip
          install
          --
          flake8
      -
        name: Lint Python code
        run: >-
          flake8
